### ISSUE TITLE
While Configuring GNUmake its unable to find libobjc

### ISSUE THREAD

**Issue by abhi-varma202** [gnustep/tools-make#26]
I'm trying to build a gnustep DLL on windows. I have first built objc.dll file following the instructions mention in [GNU-Wiki](http://wiki.gnustep.org/index.php/Installation_MSYS2)  using the libobjc2 source code and I started configuring the gnumake. while configuring its showing the following things:

```
checking for libobjc... no
checking for domains containing libraries libobjc.a, libobjc.so, libobjc.dll.a, libobjc-gnu.dylib, objc.lib... (none)
checking for domains containing headers objc/objc.h... (none)
checking for custom shared objc library domain...
checking whether objc has thread support... no
checking whether Objective-C++ is supported... yes
checking whether we should use ARC... not requested by user
checking for the flag to use to do partial linking... -r
checking for the GCC version... 11.2
checking for __objc_load... no
checking whether runtime library supports the gnustep-2.0 ABI... no
checking for runtime ABI... gcc
checking whether the compiler supports native ObjC exceptions... no
checking if the compiler supports autodependencies... yes: gcc version is 11.2 >= 3.0

```

The above command line output shows its couldn't find the libobjc and the compiler we are using doesn't support native objc exception. I want to configure make with libojc and with native objc exception support. Any help is much appreciated?

**Comment by triplef** [comment]
libobjc2 requires Clang, but doesn’t currently support MinGW (https://github.com/gnustep/libobjc2/pull/190).

If you’re open to using the MSVC toolchain instead of MinGW you could use this project instead:
https://github.com/gnustep/tools-windows-msvc

**Comment by abhi-varma202** [comment]
@triplef is there any step by step guide as to how to install liobjc and build GNUStep on windows?

**Comment by triplef** [comment]
If you’re ok with not using MinGW then yes:
https://github.com/gnustep/tools-windows-msvc#building-the-toolchain

Alternatively you can just download the pre-built binaries:
https://github.com/gnustep/tools-windows-msvc#installation

**Comment by triplef** [comment]
The toolchain _supports_ ARC, but you can decide whether you want to build your own code with or without ARC using the `-fobjc-arc` compiler flag.

**Comment by triplef** [comment]
Sounds like you are not setting the right compiler flags. Please follow the instructions here:
https://github.com/gnustep/tools-windows-msvc#using-the-toolchain-from-the-command-line

**Comment by abhi-varma202** [comment]
@triplef  I just ran the following command and it threw me this error. 
![image](https://user-images.githubusercontent.com/48425165/156341585-27176f8e-e852-46fe-99ce-6016e9d14161.png)

**Comment by abhi-varma202** [comment]
@triplef This has resolved that error. Now I'm facing another error where I'm trying to generate a dll for my code. Its showing the following error.
![image](https://user-images.githubusercontent.com/48425165/156515671-ed4c19bd-8ce4-4a4d-8e65-9d6ff498f847.png)

Any idea why this is happening. i couldn't an article for this error in google.

**Comment by triplef** [comment]
I’m guessing there’s some other error in Test.m causing this. Can you attach the whole file?

**Comment by abhi-varma202** [comment]
I was trying to create empty dll just to see whether is compiling or not

```
#import <Foundation/Foundation.h>

BOOL WINAPI DllMain(
    HINSTANCE hinstDLL,  // handle to DLL module
    DWORD fdwReason,     // reason for calling function
    LPVOID lpReserved )  // reserved
{
    // Perform actions based on the reason for calling.
    switch( fdwReason ) 
    { 
        case DLL_PROCESS_ATTACH:
         // Initialize once for each new process.
         // Return FALSE to fail DLL load.
            break;

        case DLL_THREAD_ATTACH:
         // Do thread-specific initialization.
            break;

        case DLL_THREAD_DETACH:
         // Do thread-specific cleanup.
            break;

        case DLL_PROCESS_DETACH:
         // Perform any necessary cleanup.
            break;
    }
    return TRUE;  // Successful DLL_PROCESS_ATTACH.
}
```

**Comment by triplef** [comment]
Maybe `WINAPI` is not defined? Not sure if Foundation includes the right headers. You could try including `windows.h` or just use `__stdcall` instead.

**Comment by abhi-varma202** [comment]
@triplef I have run the following command to create the dll.
```
clang -shared -v `gnustep-config --base-libs` -ldispatch -o Test.dll Test.o
```
and its throwing me the following error
```
clang version 11.0.0 (https://github.com/msys2/MSYS2-packages ca391a3660d17cdee1e94d5afd2e72a4f750cddb)
Target: x86_64-pc-windows-msys
Thread model: posix
InstalledDir: /usr/bin
 "/usr/bin/x86_64-pc-msys-gcc" -shared -v -fuse-ld=lld -fexceptions -fobjc-runtime=gnustep-2.0 -fblocks -L/home/M1060999/GNUstep/Library/Libraries -L/c/GNUstep/x64/Debug/lib -m64 -o Test.dll -lgnustep-base -lobjc -lws2_32 -ladvapi32 -lcomctl32 -luser32 -lcomdlg32 -lmpr -lnetapi32 -lkernel32 -lshell32 -lmsvcrtd -lvcruntimed -lucrtd -ldispatch Test.o
Using built-in specs.
COLLECT_GCC=/usr/bin/x86_64-pc-msys-gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-msys/11.2.0/lto-wrapper.exe
x86_64-pc-msys-gcc: error: unrecognized command-line option ‘-fobjc-runtime=gnustep-2.0’
x86_64-pc-msys-gcc: error: unrecognized command-line option ‘-fblocks’
Target: x86_64-pc-msys
Configured with: /c/S/gcc/src/gcc-11.2.0/configure --build=x86_64-pc-msys --prefix=/usr --libexecdir=/usr/lib --enable-bootstrap --enable-shared --enable-shared-libgcc --enable-static --enable-version-specific-runtime-libs --with-arch=x86-64 --with-tune=generic --disable-multilib --enable-__cxa_atexit --with-dwarf2 --enable-languages=c,c++,fortran,lto --enable-graphite --enable-threads=posix --enable-libatomic --enable-libgomp --disable-libitm --enable-libquadmath --enable-libquadmath-support --disable-libssp --disable-win32-registry --disable-symvers --with-gnu-ld --with-gnu-as --disable-isl-version-check --enable-checking=release --without-libiconv-prefix --without-libintl-prefix --with-system-zlib --enable-linker-build-id --with-default-libstdcxx-abi=gcc4-compatible --enable-libstdcxx-filesystem-ts
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 11.2.0 (GCC)
clang: error: linker (via gcc) command failed with exit code 1 (use -v to see invocation)

```

**Comment by triplef** [comment]
Looks like clang trying to use the gcc you have installed inside mys2 for linking for some reason (even though `-fuse-ld=lld` should make it use lld). Maybe try uninstalling gcc in MSYS.

**Comment by abhi-varma202** [comment]
@triplef while uninstalling gcc its saying 
```
checking dependencies...
error: failed to prepare transaction (could not satisfy dependencies)
:: removing gcc breaks dependency 'gcc' required by clang

```

**Comment by triplef** [comment]
You should usually not have any compilers installed inside the MSYS subsystem (only inside MinGW, see [here](https://www.msys2.org/wiki/MSYS2-introduction/) for the differences). Please uninstall both clang and gcc (clang is also the wrong one as indicated by the `x86_64-pc-windows-msys` target).

**Comment by abhi-varma202** [comment]
So which clang should i use?

**Comment by abhi-varma202** [comment]
@triplef I tried the following command in visual studio developer powershell 
```
clang-cl -I C:\GNUstep\x64\Release\include -fobjc-runtime=gnustep-2.0 -Xclang -fexceptions -Xclang -fobjc-exceptions -fblocks -DGNUSTEP -DGNUSTEP_WITH_DLL -DGNUSTEP_RUNTIME=1 -D_NONFRAGILE_ABI=1 -D_NATIVE_OBJC_EXCEPTIONS /MD /c Test.m
```
and this is giving the following error
```
clang-cl: error: no such file or directory: '.0'
```

**Comment by triplef** [comment]
I’ve never tried in PowerShell, could this be causing this? Can you try in a normal Visual Studio CMD?

**Comment by abhi-varma202** [comment]
@triplef Running the command on visual studio cmd work... any idea what the command is for generating DLL?

**Comment by triplef** [comment]
`clang-cl` has the same options as the MSVC compiler `cl`, so this should help:
https://stackoverflow.com/a/2220213/1534401

**Comment by abhi-varma202** [comment]
@triplef  So just linking the lib files in the following commands are enough or do i need to include any other lib files like clang or vs?
```
clang-cl test.obj gnustep-base.lib objc.lib dispatch.lib /MDd -o test.exe
```

**Comment by triplef** [comment]
Yes your exe will need to be able to load the GNUstep DLLs.

**Comment by triplef** [comment]
I’m going to mark this as resolved, but please feel free to open issues against the [tools-windows-msvc repo](https://github.com/gnustep/tools-windows-msvc) if applicable, or otherwise the [discuss-gnustep mailing list](http://gnustep.org/information/gethelp.html) is also a good place to get help.
