### ISSUE TITLE
Alpine Linux / musl C library support broken at link stage

### ISSUE THREAD

**Issue by rmottola** [gnustep/tools-make#31]
We broke build on Alpine Liunx somewhen in the past year. When building base, everything compiles, but links badly. gnustep base itself is not built as a shared library and compiling things like autogsdoc will give missing symbols of a lot of base dependencies (e.g. gz, tls, etc). The issue comes from gnustep make, since checking out older versions with current base, makes a working base.

I tracked it down between these two commits:

Broken:
```

commit 5dd6aee069089a75ef8ef7a5185dd8fe147f3b8a (HEAD)
Author: Hugo Melder <service@hugomelder.com>
Date:   Tue Aug 2 19:25:07 2022 +0200

    Cleanup config.make.in

```
Working:

```
commit fd76f00ab873d73a000f4546e52e1686331cda0c (HEAD)
Author: Richard Frith-Macdonald <rfm@gnu.org>
Date:   Wed Feb 16 09:28:34 2022 +0000

    Unless --failfast is specified, all test files should be executed.
```

**Comment by rmottola** [comment]
Already broken:

```
commit 0dee9266100ff65809c0c4ee7d2e6fcadb6c6b08 (HEAD)
Merge: 5e981820 1e690121
Author: Fred Kiefer <fredkiefer@gmx.de>
Date:   Sun Jun 12 17:20:42 2022 +0200

    Merge pull request #27 from gnustep/config_update
    
    Use newer version of config.guess and config.sub.

```

**Comment by rmottola** [comment]
Still works:
```
commit 37f5a2f9e16a4dc219e1700df8ea9377554d2bbf (HEAD -> master, origin/master, origin/HEAD)
Author: Richard Frith-Macdonald <rfm@gnu.org>
Date:   Fri Oct 21 16:37:54 2022 +0100

    tweak life of the I/O of a connection.
```

**Comment by rmottola** [comment]
I identify this a s breaking commit https://github.com/gnustep/tools-make/commit/0dee9266100ff65809c0c4ee7d2e6fcadb6c6b08

**Comment by hmelder** [comment]
Is the problem still present?

**Comment by rmottola** [comment]
Fixed by https://github.com/gnustep/tools-make/commit/58d9d3a9e5d86a4f81192845a8634b61166ceb9d
