### ISSUE TITLE
javac not found when installing

### ISSUE THREAD

**Issue by rmottola** [gnustep/tools-make#41]
When installing base or gui, I get this messages on linux:

```
which: no javac in (/home/multix/GNUstep/Tools:/Local/Tools:/System/Tools:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib/llvm/17/bin:/usr/lib/llvm/16/bin:/usr/lib/llvm/10/bin)
gmake[1]: Nothing to be done for 'install'.
```

**Comment by rmottola** [comment]
Probably related to work on this issue: https://github.com/gnustep/tools-make/issues/34

**Comment by rfm** [comment]
Should be fixed ... I rewrote to perform a check at the point when javah would normally be used, rather than a check at the point where we test whether the variable specifying its location is defined.

**Comment by rmottola** [comment]
@rfm works for me now (no errors). Hopefully it still works with javac or javah present (@gcasa ?)
